### ISSUE TITLE
Getting error when trying to download playlist

### ISSUE THREAD

**Issue by zhoul-HS** [ravishi/rdio-dl#10]
I'm using Babun (Cygwin) on windows because it seems like the setup isn't working on windows, right?

Anyways I'm getting an error:
```
/usr/lib/python2.7/site-packages/requests-2.8.1-py2.7.egg/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
[download] Downloading playlist: Indie
[Rdio] playlist Indie: Collected 219 video ids (downloading 219 of them)
[download] Downloading video 1 of 219
Traceback (most recent call last):
  File "/usr/bin/rdio-dl", line 4, in <module>
    __import__('pkg_resources').run_script('rdio-dl==0.0.3.dev0', 'rdio-dl')
  File "build/bdist.cygwin-1.7.35-i686/egg/pkg_resources/__init__.py", line 745, in run_script
  File "build/bdist.cygwin-1.7.35-i686/egg/pkg_resources/__init__.py", line 1677, in run_script
  File "/usr/lib/python2.7/site-packages/rdio_dl-0.0.3.dev0-py2.7.egg/EGG-INFO/scripts/rdio-dl", line 6, in <module>

  File "/usr/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "build/bdist.cygwin-1.7.35-i686/egg/rdio_dl/cli.py", line 55, in main
  File "/usr/lib/python2.7/site-packages/youtube_dl-2015.12.6-py2.7.egg/youtube_dl/YoutubeDL.py", line 1669, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python2.7/site-packages/youtube_dl-2015.12.6-py2.7.egg/youtube_dl/YoutubeDL.py", line 674, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python2.7/site-packages/youtube_dl-2015.12.6-py2.7.egg/youtube_dl/YoutubeDL.py", line 835, in process_ie_result
    extra_info=extra)
  File "/usr/lib/python2.7/site-packages/youtube_dl-2015.12.6-py2.7.egg/youtube_dl/YoutubeDL.py", line 727, in process_ie_result
    extra_info=extra_info)
  File "/usr/lib/python2.7/site-packages/youtube_dl-2015.12.6-py2.7.egg/youtube_dl/YoutubeDL.py", line 674, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python2.7/site-packages/youtube_dl-2015.12.6-py2.7.egg/youtube_dl/YoutubeDL.py", line 720, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python2.7/site-packages/youtube_dl-2015.12.6-py2.7.egg/youtube_dl/YoutubeDL.py", line 1299, in process_video_result
    format['http_headers'] = self._calc_headers(full_format_info)
  File "/usr/lib/python2.7/site-packages/youtube_dl-2015.12.6-py2.7.egg/youtube_dl/YoutubeDL.py", line 1185, in _calc_headers
    cookies = self._calc_cookies(info_dict)
  File "/usr/lib/python2.7/site-packages/youtube_dl-2015.12.6-py2.7.egg/youtube_dl/YoutubeDL.py", line 1192, in _calc_cookies
    pr = sanitized_Request(info_dict['url'])
  File "/usr/lib/python2.7/site-packages/youtube_dl-2015.12.6-py2.7.egg/youtube_dl/utils.py", line 380, in sanitized_Request
    'http:%s' % url if url.startswith('//') else url, *args, **kwargs)
AttributeError: 'NoneType' object has no attribute 'startswith'
````

**Comment by zhoul-HS** [comment]
I think i've figured it out, the first track in my playlist is no available anymore, so i'm guessing it doesn't resolve, but instead of skipping it, it crashes.

**Comment by ravishi** [comment]
Hey, I've added the `--ignore-errors` flag to deal with this kind of cases. Can you confirm if it works?

**Comment by dan-dr** [comment]
it works! 5 days to shutdown :(

**Comment by ravishi** [comment]
Nice!
